//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager
{
    using System;
    
    public partial class Sp_ListTask_Result1
    {
        public Nullable<int> Score { get; set; }
        public Nullable<int> DDate { get; set; }
    }
}
